sources:
  base:
    table: 11111-02-01-4
    skip: 6
    names:
      - date
      - rs
      - name
      - munis
  area:
    table: 11111-01-01-4
    skip: 6
    names:
      - date
      - rs
      - name
      - area
    subset:
      - rs
      - area
  population:
    table: 12411-01-01-4
    skip: 8
    names:
      - rs
      - name
      - t_pop
      - m_pop
      - f_pop
    subset:
      - rs
      - t_pop
      - m_pop
      - f_pop

